#### 1. Import the numpy package under the name `np` (★☆☆)


In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)


In [5]:
print(np.__version__)
np.show_config()

1.24.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)


In [7]:
n = np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)


In [8]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [10]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (2787590163.py, line 1)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [11]:
n = np.zeros(10)
n[4] =1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [12]:
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)


In [13]:
n = np.arange(50)
n=n[::-1]
print(n)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [14]:
n = np.arange(9).reshape(3,3)
print(n)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [15]:
non_xero = np.nonzero([1,2,0,0,4,0])
print(non_xero)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)


In [16]:
n_identity = np.eye(3)
print(n_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)


In [17]:
n = np.random.random((3,3,3))
print(n)

[[[0.77734349 0.06981838 0.74632544]
  [0.53736012 0.5751063  0.73580032]
  [0.98789393 0.34918378 0.44541538]]

 [[0.07542077 0.15406164 0.79398978]
  [0.75899429 0.11393671 0.0318867 ]
  [0.25733512 0.71231575 0.8220564 ]]

 [[0.02486957 0.58922962 0.13764877]
  [0.67924863 0.34271618 0.05326492]
  [0.20861135 0.21889207 0.30216157]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [20]:
n = np.random.random((10,10))
print(n)
print("Max is :",n.max())
print("Min is :",n.min())



[[9.79731071e-01 3.54460259e-01 1.16486256e-01 1.91898479e-01
  6.36580004e-01 8.77875228e-01 7.20753451e-01 3.06634894e-01
  9.91889617e-01 1.65915343e-01]
 [8.80504332e-01 6.36598500e-01 2.70092452e-01 5.10847419e-01
  7.92921614e-04 6.14301027e-01 7.24011753e-01 2.86750961e-01
  3.64156384e-01 5.31454691e-01]
 [9.00315486e-01 1.21365377e-01 3.23277625e-01 3.73513158e-01
  6.79401764e-01 7.82454884e-01 7.81184598e-01 8.56187834e-01
  7.57042657e-01 5.89040287e-01]
 [4.34081111e-01 8.05846440e-02 1.81633798e-01 1.84151068e-01
  8.15729449e-02 7.82289768e-01 4.15628878e-01 5.21126354e-01
  2.59933900e-01 8.26604820e-01]
 [2.31199401e-01 7.23899497e-01 4.62950390e-01 6.85752691e-02
  3.33515063e-03 2.91775895e-01 9.31890039e-01 1.68922990e-01
  7.40745752e-01 7.56750661e-01]
 [3.26724962e-01 7.07270286e-01 4.99315295e-01 6.56379245e-01
  4.52487070e-01 5.46365942e-01 1.33727885e-01 5.03797233e-02
  3.49117084e-01 3.94898205e-01]
 [5.29501988e-01 7.41031812e-01 1.92571641e-01 8.05950195e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)


In [22]:
n = np.random.random(30)
print(n)
print("Mean value is :",n.mean())

[0.50380533 0.77008933 0.36686637 0.82407626 0.06362661 0.34138385
 0.44374325 0.56632898 0.06188393 0.42036109 0.61896803 0.77850044
 0.53983921 0.02619212 0.61780038 0.13716728 0.87783042 0.3443813
 0.45504836 0.07415614 0.27653918 0.68598071 0.87433936 0.7176248
 0.29569256 0.44818072 0.29098926 0.33907104 0.29117904 0.17624692]
Mean value is : 0.44092974158695486


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [23]:
n = np.ones((10,10))
n[1:-1,1:-1] = 0
print(n)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [26]:
n = np.ones((10,10))
# n = np.pad(n, pad_width=1, mode='constant', constant_values=0)
n[:, [0, -1]] = 0
n[[0, -1], :] = 0
print(n)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)


In [27]:
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [29]:
n = np.diag(1+np.arange(4),k=-1)
print(n)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [31]:
n = np.zeros((8,8),dtype=int)
n[1::2,::2] = 1
n[::2,1::2] = 1
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [32]:
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


In [33]:
n = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)


In [34]:
n = np.random.random((5,5))
n = (n - np.mean (n)) / (np.std (n))
print(n)

[[ 1.19427223  0.8198899  -0.72285664  0.63969772  0.332374  ]
 [-1.33694253 -0.97124258  0.45333476 -0.06943084  0.61763685]
 [-1.33226873 -0.68534149  0.8426105  -0.60684492  0.0616891 ]
 [ 1.31501595  1.06355219  1.13448044 -0.93938147 -1.52788267]
 [ 1.3680901  -0.82825676 -0.48143221  1.41047656 -1.75123945]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [36]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [38]:
n = np.dot(np.ones((5,3)), np.ones((3,2)))
print(n)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [39]:
n = np.arange(11)
n[(3 < n) & (n < 8)] *= -1
print(n)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)


In [45]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)


In [47]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

#### 28. What are the result of the following expressions? (★☆☆)


In [50]:
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_1892/480174526.py:5: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_1892/480174526.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_1892/480174526.py:7: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)


In [52]:
n = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(n)), n))

# OR
print(np.where(n>0, np.ceil(n), np.floor(n)))


[-5.  7.  2.  7.  9. -3. -9.  6. -2. -5.]
[-5.  7.  2.  7.  9. -3. -9.  6. -2. -5.]


#### 30. How to find common values between two arrays? (★☆☆)


In [54]:
n1 = np.random.randint(0,10,10)
n2 = np.random.randint(0,10,10)
print(n1)
print(n2)
print(np.intersect1d(n1,n2))

[1 1 6 2 3 1 4 4 6 9]
[1 3 6 9 6 8 1 5 4 0]
[1 3 4 6 9]


#### 31. Is the following expressions true? (★☆☆)


In [56]:
np.sqrt(-1) == np.emath.sqrt(-1)


/tmp/ipykernel_1892/2961820512.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 32. How to get the dates of yesterday, today and tomorrow? (★☆☆)


In [58]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2023-03-05
2023-03-06
2023-03-07


#### 33. How to get all the dates corresponding to the month of July 2016? (★★☆)


In [59]:
n = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(n)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 34. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


In [60]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 35. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


In [61]:
n = np.random.uniform(0,10,10)

print(n - n%1)
print(n // 1)
print(np.floor(n))
print(n.astype(int))
print(np.trunc(n))

[2. 9. 5. 6. 3. 3. 9. 4. 6. 7.]
[2. 9. 5. 6. 3. 3. 9. 4. 6. 7.]
[2. 9. 5. 6. 3. 3. 9. 4. 6. 7.]
[2 9 5 6 3 3 9 4 6 7]
[2. 9. 5. 6. 3. 3. 9. 4. 6. 7.]


#### 36. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [62]:
n = np.zeros((5,5))
n += np.arange(5)
print(n)

# without broadcasting
n = np.tile(np.arange(0, 5), (5,1))
print(n)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 37. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [63]:
def generate():
    for x in range(10):
        yield x
n = np.fromiter(generate(),dtype=float,count=-1)
print(n)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 38. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [64]:
n = np.linspace(0,1,11,endpoint=False)[1:]
print(n)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 39. Create a random vector of size 10 and sort it (★★☆)


In [66]:
n = np.random.random(10)
print(n)
n.sort()
print(n)

[0.68369875 0.30571541 0.42406745 0.09136207 0.13984255 0.4455055
 0.8852964  0.93778148 0.75261514 0.51874327]
[0.09136207 0.13984255 0.30571541 0.42406745 0.4455055  0.51874327
 0.68369875 0.75261514 0.8852964  0.93778148]


#### 40. How to sum a small array faster than np.sum? (★★☆)


In [68]:
n = np.arange(10)
print(n)
n = np.add.reduce(n)
print(n)

[0 1 2 3 4 5 6 7 8 9]
45
