#### 1. Import the numpy package under the name `np` (★☆☆)


In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)


In [5]:
print(np.__version__)
np.show_config()

1.24.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)


In [7]:
n = np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)


In [8]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [10]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (2787590163.py, line 1)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [11]:
n = np.zeros(10)
n[4] =1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [12]:
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)


In [13]:
n = np.arange(50)
n=n[::-1]
print(n)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [14]:
n = np.arange(9).reshape(3,3)
print(n)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [15]:
non_xero = np.nonzero([1,2,0,0,4,0])
print(non_xero)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)


In [16]:
n_identity = np.eye(3)
print(n_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)


In [17]:
n = np.random.random((3,3,3))
print(n)

[[[0.77734349 0.06981838 0.74632544]
  [0.53736012 0.5751063  0.73580032]
  [0.98789393 0.34918378 0.44541538]]

 [[0.07542077 0.15406164 0.79398978]
  [0.75899429 0.11393671 0.0318867 ]
  [0.25733512 0.71231575 0.8220564 ]]

 [[0.02486957 0.58922962 0.13764877]
  [0.67924863 0.34271618 0.05326492]
  [0.20861135 0.21889207 0.30216157]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [20]:
n = np.random.random((10,10))
print(n)
print("Max is :",n.max())
print("Min is :",n.min())



[[9.79731071e-01 3.54460259e-01 1.16486256e-01 1.91898479e-01
  6.36580004e-01 8.77875228e-01 7.20753451e-01 3.06634894e-01
  9.91889617e-01 1.65915343e-01]
 [8.80504332e-01 6.36598500e-01 2.70092452e-01 5.10847419e-01
  7.92921614e-04 6.14301027e-01 7.24011753e-01 2.86750961e-01
  3.64156384e-01 5.31454691e-01]
 [9.00315486e-01 1.21365377e-01 3.23277625e-01 3.73513158e-01
  6.79401764e-01 7.82454884e-01 7.81184598e-01 8.56187834e-01
  7.57042657e-01 5.89040287e-01]
 [4.34081111e-01 8.05846440e-02 1.81633798e-01 1.84151068e-01
  8.15729449e-02 7.82289768e-01 4.15628878e-01 5.21126354e-01
  2.59933900e-01 8.26604820e-01]
 [2.31199401e-01 7.23899497e-01 4.62950390e-01 6.85752691e-02
  3.33515063e-03 2.91775895e-01 9.31890039e-01 1.68922990e-01
  7.40745752e-01 7.56750661e-01]
 [3.26724962e-01 7.07270286e-01 4.99315295e-01 6.56379245e-01
  4.52487070e-01 5.46365942e-01 1.33727885e-01 5.03797233e-02
  3.49117084e-01 3.94898205e-01]
 [5.29501988e-01 7.41031812e-01 1.92571641e-01 8.05950195e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)


In [22]:
n = np.random.random(30)
print(n)
print("Mean value is :",n.mean())

[0.50380533 0.77008933 0.36686637 0.82407626 0.06362661 0.34138385
 0.44374325 0.56632898 0.06188393 0.42036109 0.61896803 0.77850044
 0.53983921 0.02619212 0.61780038 0.13716728 0.87783042 0.3443813
 0.45504836 0.07415614 0.27653918 0.68598071 0.87433936 0.7176248
 0.29569256 0.44818072 0.29098926 0.33907104 0.29117904 0.17624692]
Mean value is : 0.44092974158695486


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [23]:
n = np.ones((10,10))
n[1:-1,1:-1] = 0
print(n)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [26]:
n = np.ones((10,10))
# n = np.pad(n, pad_width=1, mode='constant', constant_values=0)
n[:, [0, -1]] = 0
n[[0, -1], :] = 0
print(n)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)


In [27]:
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [29]:
n = np.diag(1+np.arange(4),k=-1)
print(n)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [31]:
n = np.zeros((8,8),dtype=int)
n[1::2,::2] = 1
n[::2,1::2] = 1
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [32]:
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


In [33]:
n = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)


In [34]:
n = np.random.random((5,5))
n = (n - np.mean (n)) / (np.std (n))
print(n)

[[ 1.19427223  0.8198899  -0.72285664  0.63969772  0.332374  ]
 [-1.33694253 -0.97124258  0.45333476 -0.06943084  0.61763685]
 [-1.33226873 -0.68534149  0.8426105  -0.60684492  0.0616891 ]
 [ 1.31501595  1.06355219  1.13448044 -0.93938147 -1.52788267]
 [ 1.3680901  -0.82825676 -0.48143221  1.41047656 -1.75123945]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [36]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [38]:
n = np.dot(np.ones((5,3)), np.ones((3,2)))
print(n)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [39]:
n = np.arange(11)
n[(3 < n) & (n < 8)] *= -1
print(n)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)


In [45]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)


In [47]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

#### 28. What are the result of the following expressions? (★☆☆)


In [50]:
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_1892/480174526.py:5: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_1892/480174526.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_1892/480174526.py:7: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)


In [52]:
n = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(n)), n))

# OR
print(np.where(n>0, np.ceil(n), np.floor(n)))


[-5.  7.  2.  7.  9. -3. -9.  6. -2. -5.]
[-5.  7.  2.  7.  9. -3. -9.  6. -2. -5.]


#### 30. How to find common values between two arrays? (★☆☆)


In [54]:
n1 = np.random.randint(0,10,10)
n2 = np.random.randint(0,10,10)
print(n1)
print(n2)
print(np.intersect1d(n1,n2))

[1 1 6 2 3 1 4 4 6 9]
[1 3 6 9 6 8 1 5 4 0]
[1 3 4 6 9]


#### 31. Is the following expressions true? (★☆☆)


In [56]:
np.sqrt(-1) == np.emath.sqrt(-1)


/tmp/ipykernel_1892/2961820512.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 32. How to get the dates of yesterday, today and tomorrow? (★☆☆)


In [58]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2023-03-05
2023-03-06
2023-03-07


#### 33. How to get all the dates corresponding to the month of July 2016? (★★☆)


In [59]:
n = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(n)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 34. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


In [60]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 35. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


In [61]:
n = np.random.uniform(0,10,10)

print(n - n%1)
print(n // 1)
print(np.floor(n))
print(n.astype(int))
print(np.trunc(n))

[2. 9. 5. 6. 3. 3. 9. 4. 6. 7.]
[2. 9. 5. 6. 3. 3. 9. 4. 6. 7.]
[2. 9. 5. 6. 3. 3. 9. 4. 6. 7.]
[2 9 5 6 3 3 9 4 6 7]
[2. 9. 5. 6. 3. 3. 9. 4. 6. 7.]


#### 36. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [62]:
n = np.zeros((5,5))
n += np.arange(5)
print(n)

# without broadcasting
n = np.tile(np.arange(0, 5), (5,1))
print(n)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 37. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [63]:
def generate():
    for x in range(10):
        yield x
n = np.fromiter(generate(),dtype=float,count=-1)
print(n)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 38. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [64]:
n = np.linspace(0,1,11,endpoint=False)[1:]
print(n)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 39. Create a random vector of size 10 and sort it (★★☆)


In [66]:
n = np.random.random(10)
print(n)
n.sort()
print(n)

[0.68369875 0.30571541 0.42406745 0.09136207 0.13984255 0.4455055
 0.8852964  0.93778148 0.75261514 0.51874327]
[0.09136207 0.13984255 0.30571541 0.42406745 0.4455055  0.51874327
 0.68369875 0.75261514 0.8852964  0.93778148]


#### 40. How to sum a small array faster than np.sum? (★★☆)


In [68]:
n = np.arange(10)
print(n)
n = np.add.reduce(n)
print(n)

[0 1 2 3 4 5 6 7 8 9]
45


#### 41. Consider two random array A and B, check if they are equal (★★☆)


In [69]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 42. Make an array immutable (read-only) (★★☆)


In [70]:
n = np.zeros(10)
n.flags.writeable = False
n[0] = 1

ValueError: assignment destination is read-only

#### 43. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [71]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.90624351 0.29067768 0.58411303 0.99675638 0.60012027 0.9669693
 0.76203148 0.79802551 0.9529748  0.68215672]
[0.05339732 1.37457391 0.27492106 0.63031283 0.61666659 0.5446508
 0.7467303  0.31040337 1.12653443 0.57842822]


#### 44. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [72]:
n = np.random.random(10)
n[n.argmax()] = 0
print(n)

[0.64103155 0.05328034 0.00096853 0.36683395 0.3842079  0.21354757
 0.54998273 0.31594772 0.32518103 0.        ]


#### 45. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)


In [73]:
n = np.zeros((5,5), [('x',float),('y',float)])
n['x'], n['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(n)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 46. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)


In [74]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 47. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


In [75]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 48. How to print all the values of an array? (★★☆)


In [76]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 49. How to find the closest value (to a given scalar) in a vector? (★★☆)


In [77]:
n = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(n-v)).argmin()
print(n[index])

59


#### 50. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)


In [78]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/tmp/ipykernel_1892/274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 51. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


In [81]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.66788147 0.71675825 0.37922514 0.91910397 0.60872879
  0.69872781 0.49759237 0.76857221 0.84258921]
 [0.66788147 0.         0.13823331 0.28874544 0.2632336  0.59215275
  0.7523384  0.20936872 0.7510036  0.44718782]
 [0.71675825 0.13823331 0.         0.34933442 0.30827484 0.72526881
  0.88594106 0.21965488 0.88764743 0.57810044]
 [0.37922514 0.28874544 0.34933442 0.         0.54409903 0.50517522
  0.65565798 0.14609077 0.68809974 0.56194698]
 [0.91910397 0.2632336  0.30827484 0.54409903 0.         0.69670404
  0.84289054 0.47100776 0.81392509 0.40468866]
 [0.60872879 0.59215275 0.72526881 0.50517522 0.69670404 0.
  0.16077665 0.61890688 0.18344332 0.37087411]
 [0.69872781 0.7523384  0.88594106 0.65565798 0.84289054 0.16077665
  0.         0.77576874 0.08794766 0.48228248]
 [0.49759237 0.20936872 0.21965488 0.14609077 0.47100776 0.61890688
  0.77576874 0.         0.79786885 0.59509731]
 [0.76857221 0.7510036  0.88764743 0.68809974 0.81392509 0.18344332
  0.08794766 0.79786

#### 52. How to convert a float (32 bits) array into an integer (32 bits) in place?


In [80]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[35 89 80 38 83 15 20 50 76 44]


#### 53. How to read the following file? (★★☆)


In [82]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### 54. What is the equivalent of enumerate for numpy arrays? (★★☆)


In [83]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 55. Generate a generic 2D Gaussian-like array (★★☆)


In [84]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 56. How to randomly place p elements in a 2D array? (★★☆)


In [85]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


#### 57. Subtract the mean of each row of a matrix (★★☆)


In [86]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.04309267  0.12544689 -0.28344761  0.00653735  0.26649998  0.31844903
  -0.45107894 -0.37428779  0.47071511 -0.03574135]
 [-0.19811952  0.55919779 -0.33260006  0.12298206 -0.15808087 -0.33020104
  -0.1436513   0.51980599 -0.32892232  0.28958927]
 [ 0.2179499  -0.28734263 -0.06309321  0.20368666  0.17926304 -0.11619221
  -0.31989634  0.228317    0.25160081 -0.29429302]
 [-0.34731894 -0.18779475 -0.00963219  0.38131145  0.04668464  0.09168874
  -0.20126163 -0.07859032  0.46182886 -0.15691587]
 [-0.45928683  0.39368722  0.40254407 -0.46483714  0.4773699  -0.21249632
   0.27160468 -0.36839595 -0.41404081  0.37385118]]


#### 58. How to sort an array by the nth column? (★★☆)


In [87]:
n = np.random.randint(0,10,(3,3))
print(n)
print(n[n[:,1].argsort()])

[[8 7 3]
 [3 4 3]
 [3 2 5]]
[[3 2 5]
 [3 4 3]
 [8 7 3]]


#### 59. How to tell if a given 2D array has null columns? (★★☆)


In [88]:
n = np.random.randint(0,3,(3,10))
print((~n.any(axis=0)).any())

# null : np.nan
n=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(n).all(axis=0))

False
[False False  True]


#### 60. Find the nearest value from a given value in an array (★★☆)


In [89]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5442071330154516


#### 61. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [90]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 62. Create an array class that has a name attribute (★★☆)


In [91]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 63. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


In [92]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[2. 1. 2. 6. 2. 2. 3. 6. 4. 2.]
[ 3.  1.  3. 11.  3.  3.  5. 11.  7.  3.]


#### 64. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


In [93]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 65. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


In [94]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


#### 66. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


In [95]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 67 66 56]
 [42 46 55 66]
 [39 52 61 47]]
[[58 67 66 56]
 [42 46 55 66]
 [39 52 61 47]]


#### 67. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)


In [96]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.4890814  0.50855694 0.60448636 0.3189075  0.52172472 0.45060511
 0.54660509 0.37306507 0.40310298 0.53789959]
0    0.489081
1    0.508557
2    0.604486
3    0.318908
4    0.521725
5    0.450605
6    0.546605
7    0.373065
8    0.403103
9    0.537900
dtype: float64


#### 68. How to get the diagonal of a dot product? (★★★)


In [97]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.6260007 , 1.34107242, 1.54845343, 1.00776103, 2.29643762])

#### 69. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


In [98]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 70. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)


In [99]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 71. How to swap two rows of an array? (★★★)


In [101]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 72. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)


In [102]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 26) ( 0, 27) ( 3, 27) ( 3, 45) ( 5, 50) ( 5, 75) (10, 26) (10, 55)
 (14, 58) (14, 65) (20, 74) (20, 76) (23, 48) (23, 66) (26, 27) (26, 55)
 (27, 45) (33, 80) (33, 99) (48, 66) (50, 75) (53, 75) (53, 82) (58, 65)
 (74, 76) (75, 82) (80, 99) (89, 92) (92, 92)]


#### 73. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


In [103]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 74. How to compute averages using a sliding window over an array? (★★★)


In [105]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 75. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


In [107]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 76. How to negate a boolean, or to change the sign of a float inplace? (★★★)


In [108]:
n = np.random.randint(0,2,100)
np.logical_not(n, out=n)

n = np.random.uniform(-1.0,1.0,100)
np.negative(n, out=n)

array([-0.54896307, -0.87413765, -0.43251174,  0.52684449,  0.6258393 ,
        0.70077886, -0.68207258,  0.80498067,  0.03619661,  0.04248689,
        0.15204704,  0.76525316,  0.80093171,  0.37727792, -0.03544541,
        0.2290301 ,  0.86003654, -0.60373717, -0.19164631,  0.25648086,
       -0.07779887, -0.0210853 , -0.8575839 , -0.20471895, -0.26350453,
        0.9322528 ,  0.98114225,  0.45322132, -0.69543485,  0.65373028,
       -0.68116582, -0.9465989 ,  0.95109193,  0.34425293, -0.26597516,
        0.52995123,  0.95212077,  0.10387737,  0.02349835, -0.36623299,
        0.92857786, -0.20742391,  0.01248205,  0.65928564,  0.68654098,
       -0.71563699, -0.58954099, -0.91307529, -0.39911052,  0.22329566,
        0.19758704, -0.59136724,  0.80711833,  0.00604338, -0.93777404,
       -0.76612907,  0.91727895,  0.59952218, -0.65110022, -0.14246474,
       -0.42478487,  0.58368222, -0.08437759, -0.42530566,  0.9299542 ,
        0.27614619, -0.13658344,  0.34318294,  0.54611805,  0.09

#### 77. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


In [109]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.67470935  7.15284311  1.77523937  0.16381822 12.12859798  2.4430145
  1.89394429  8.07213048  0.53279869  3.710671  ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


In [110]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.64610728  2.2906248   2.96680116 14.4712106  13.53692749 15.93672385
   1.58130608  0.30856761  3.31503947  6.85070945]
 [ 4.39711438  9.30545286 11.83554496  2.15859896  5.03004277  2.94202765
   3.68362834  9.18645883  6.63635571  0.23548373]
 [14.19564157  7.01474929  6.48727331 17.25267752  0.7778032   9.21197019
  14.69403002  9.1334376  11.20101844  8.31866554]
 [ 4.87871564  4.77483295  0.57984205 16.92260351 13.87682567 17.71844523
   3.62369783  2.07903408  5.76641059  6.86325345]
 [ 3.58830534  2.03561257  2.423589   13.91801479 11.10259791 14.13191958
   2.85174571  0.23244696  3.58050611  4.41275566]
 [ 5.05620621  4.50400959  0.55684351 16.54700804 12.97763784 16.94144524
   3.9328487   2.10119666  5.68496716  5.9863768 ]
 [ 6.65016557  2.35847955  1.92791009  7.77712677  3.85965163  1.27302444
   8.09777473  0.7142311   2.33947394 10.19328351]
 [ 5.67783096  3.09595007  2.84481515  7.12908743  3.32646871  1.17270836
   7.10032601  0.20230141  1.47509824  9.55308303]


#### 79. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)


In [113]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 80. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


In [114]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)



Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 81. Compute a matrix rank (★★★)

In [115]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 82. How to find the most frequent value in an array?


In [120]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[9 8 3 7 6 3 7 3 9 2 1 1 6 2 2 6 4 7 3 5 4 0 5 1 6 2 8 6 8 0 4 4 7 6 8 0 7
 4 2 7 1 0 9 2 3 4 3 0 5 4]
4


#### 83. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


In [121]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[2 1 3]
   [2 1 3]
   [3 2 3]]

  [[1 3 1]
   [1 3 0]
   [2 3 2]]

  [[3 1 3]
   [3 0 2]
   [3 2 0]]

  [[1 3 3]
   [0 2 2]
   [2 0 1]]

  [[3 3 2]
   [2 2 1]
   [0 1 2]]

  [[3 2 1]
   [2 1 3]
   [1 2 3]]

  [[2 1 1]
   [1 3 0]
   [2 3 2]]

  [[1 1 1]
   [3 0 0]
   [3 2 4]]]


 [[[2 1 3]
   [3 2 3]
   [1 2 3]]

  [[1 3 0]
   [2 3 2]
   [2 3 3]]

  [[3 0 2]
   [3 2 0]
   [3 3 2]]

  [[0 2 2]
   [2 0 1]
   [3 2 2]]

  [[2 2 1]
   [0 1 2]
   [2 2 2]]

  [[2 1 3]
   [1 2 3]
   [2 2 0]]

  [[1 3 0]
   [2 3 2]
   [2 0 0]]

  [[3 0 0]
   [3 2 4]
   [0 0 2]]]


 [[[3 2 3]
   [1 2 3]
   [2 2 1]]

  [[2 3 2]
   [2 3 3]
   [2 1 3]]

  [[3 2 0]
   [3 3 2]
   [1 3 3]]

  [[2 0 1]
   [3 2 2]
   [3 3 0]]

  [[0 1 2]
   [2 2 2]
   [3 0 3]]

  [[1 2 3]
   [2 2 0]
   [0 3 4]]

  [[2 3 2]
   [2 0 0]
   [3 4 2]]

  [[3 2 4]
   [0 0 2]
   [4 2 1]]]


 [[[1 2 3]
   [2 2 1]
   [2 4 3]]

  [[2 3 3]
   [2 1 3]
   [4 3 3]]

  [[3 3 2]
   [1 3 3]
   [3 3 3]]

  [[3 2 2]
   [3 3 0]
   [3 3 0]]

  [[2 2 2]
   

#### 84. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


In [122]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1  0  2  6  4]
 [ 0  1 13  7  9]
 [ 2 13  7 42  9]
 [ 6  7 42  6 11]
 [ 4  9  9 11  6]]


#### 85. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


In [123]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 86. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)


In [124]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))


Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 87. How to implement the Game of Life using numpy arrays? (★★★)


In [125]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 88. How to get the n largest values of an array (★★★)


In [126]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9996 9997 9995]


#### 89. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)


In [127]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 90. How to create a record array from a regular array? (★★★)


In [128]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 91. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)


In [129]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

5.52 s ± 1.31 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.08 s ± 136 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.3 s ± 762 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 92. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)


In [130]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[4]


#### 93. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


In [131]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 0 2]
 [3 0 2]
 [4 0 2]
 [2 2 4]
 [0 4 3]
 [1 1 2]
 [4 4 1]
 [1 4 0]
 [0 4 1]
 [4 4 3]]
[[1 0 2]
 [3 0 2]
 [4 0 2]
 [2 2 4]
 [0 4 3]
 [1 1 2]
 [4 4 1]
 [1 4 0]
 [0 4 1]
 [4 4 3]]
[[1 0 2]
 [3 0 2]
 [4 0 2]
 [2 2 4]
 [0 4 3]
 [1 1 2]
 [4 4 1]
 [1 4 0]
 [0 4 1]
 [4 4 3]]


#### 94. Convert a vector of ints into a matrix binary representation (★★★)


In [132]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 95. Given a two dimensional array, how to extract unique rows? (★★★)


In [133]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]]
[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


#### 96. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


In [134]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.31672003, 0.13581966, 0.22338597, 0.33686907, 0.21156617,
        0.12091556, 0.43941309, 0.02098635, 0.42963786, 0.58121265],
       [0.2698272 , 0.11571052, 0.19031196, 0.28699303, 0.18024218,
        0.10301308, 0.37435462, 0.01787916, 0.36602669, 0.49515967],
       [0.35309605, 0.15141885, 0.24904235, 0.37555926, 0.23586502,
        0.13480299, 0.48988069, 0.02339668, 0.47898275, 0.64796625],
       [0.03127607, 0.01341218, 0.02205934, 0.03326579, 0.02089214,
        0.0119404 , 0.043392  , 0.0020724 , 0.0424267 , 0.05739469],
       [0.07850561, 0.03366571, 0.05537083, 0.08349997, 0.05244105,
        0.02997142, 0.10891762, 0.0052019 , 0.10649463, 0.14406558],
       [0.4269163 , 0.18307533, 0.30110855, 0.45407579, 0.28517629,
        0.16298566, 0.5922979 , 0.02828812, 0.57912158, 0.78343372],
       [0.31970238, 0.13709858, 0.22548945, 0.34004116, 0.21355835,
        0.12205414, 0.44355077, 0.02118396, 0.43368349, 0.58668556],
       [0.3613013 , 0.15493753, 0.2548296

#### 97. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


In [135]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 98. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


In [136]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 99. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)


In [137]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.22989414  0.19194726]


### 100. Calculate sum of two numbers

In [140]:
a = 5
b = 10
c = a+b
c

15